# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
    
# Env variable
env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  REPO_NAME: ${{secrets.REPO_NAME}}

jobs:
  build:
    name: Build and Pushing the Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: docker login
      run: | # log into docker hub account
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD  
    
    - name: Get current date # get the date of the build
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"
    
    - name: Build the Docker image # push The image to the docker hub
      run: |
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          docker build . --file Dockerfile --tag $DOCKER_USER/$REPO_NAME:${GITHUB_REF##*/}-$git_hash
          docker push $DOCKER_USER/$REPO_NAME:${GITHUB_REF##*/}-$git_hash
    #- name: Update Version
    #  run: |
    #      git_hash=$(git rev-parse --short "$GITHUB_SHA")
    #      version=$(cat ./charts/helm-example/values.yaml | grep version: | awk '{print $2}')
    #      sed -i "s/$version/${GITHUB_REF##*/}-$git_hash/" ./charts/helm-example/values.yaml
          
    #- name: Commit and push changes
    #  uses: devops-infra/action-commit-push@v0.3
    #  with:
    #    github_token: ${{ secrets.GIT_TOKEN }}
    #    commit_message: Version updated
